using Baubit.DI;

namespace SampleConsoleApp
{
    /// <summary>
    /// Sample module registry that registers all sample modules.
    /// The Register() method will be generated by the source generator.
    /// </summary>
    [GeneratedModuleRegistry]
    internal static partial class SampleModuleRegistry
    {
        // The Register() method is generated by the source generator
    }
}
