using Baubit.DI;

namespace Baubit.DI.Autofac.Test
{
    /// <summary>
    /// Test module registry that registers all test modules.
    /// The Register() method will be generated by the source generator.
    /// </summary>
    [GeneratedModuleRegistry]
    internal static partial class TestModuleRegistry
    {
        // The Register() method is generated by the source generator
        // and called by TestFramework before any tests run
    }
}
